import React, { useEffect, useState } from 'react';
import { Search, ClipboardList, RefreshCw } from 'lucide-react';
import api from '../api/axios';
import { useAuth } from '../context/AuthContext';

export default function AdminActivityLogsPage() {
  const { showToast } = useAuth(); const [logs, setLogs] = useState([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState('');
  const load = async () => { setLoading(true); try { const r = await api.get('/admin/activity-logs'); setLogs(r.data || []); } catch { showToast('Unable to load activity logs', 'error'); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const filtered = logs.filter(l => JSON.stringify(l).toLowerCase().includes(query.toLowerCase()));
  return <main className="space-y-6 p-5 lg:p-8"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h2 className="text-2xl font-extrabold text-white">Activity Logs</h2><p className="mt-1 text-sm text-slate-400">Review recorded activities and their calculated carbon impact.</p></div><button onClick={load} className="inline-flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-800 px-3 py-2 text-xs font-bold text-slate-200"><RefreshCw className={'h-4 w-4 ' + (loading ? 'animate-spin' : '')}/>Refresh</button></div><div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="relative max-w-md"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-500"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search user, category, activity…" className="w-full rounded-xl border border-slate-700 bg-slate-950 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-emerald-500"/></div><p className="mt-3 text-xs text-slate-500">Showing {filtered.length} activity records</p></div><section className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900/60">{loading ? <div className="p-12 text-center text-slate-400">Loading activity logs…</div> : !filtered.length ? <div className="p-12 text-center"><ClipboardList className="mx-auto mb-3 h-10 w-10 text-slate-600"/><p className="font-semibold text-slate-300">No activities found</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-950 text-xs uppercase tracking-wider text-slate-500"><tr>{['Date','User','Category','Activity','Quantity','Total emission'].map(x=><th className="px-5 py-4" key={x}>{x}</th>)}</tr></thead><tbody className="divide-y divide-slate-800">{filtered.map((log,i)=><tr key={log.activityLogId || i} className="hover:bg-slate-800/40"><td className="px-5 py-4 text-slate-400">{log.activityDate || '-'}</td><td className="px-5 py-4 font-medium text-white">{log.username || log.userName || '-'}</td><td className="px-5 py-4"><span className="rounded-full bg-teal-500/10 px-2 py-1 text-xs font-bold text-teal-300">{log.categoryName || '-'}</span></td><td className="px-5 py-4">{log.activityTypeName || '-'}</td><td className="px-5 py-4 text-emerald-300">{log.quantity || '-'} {log.unit || ''}</td><td className="px-5 py-4 font-bold text-emerald-400">{Number(log.totalEmission || 0).toFixed(2)} kg CO₂e</td></tr>)}</tbody></table></div>}</section></main>;
}
